# Generated by Django 5.2.8 on 2025-11-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
    ]
