# Generated by Django 5.2.8 on 2025-11-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_your_migration_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-record_date']},
        ),
    ]
