"""
Django settings for GatituProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%0h+m(1%yx_8o$re=&z7h73lqc%7fihzhvdpj(j(g(yv@7_=sc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Keep as True for now to see errors

# Security settings
SECURE_SSL_REDIRECT = False

# CSRF Comprehensive Fix
ALLOWED_HOSTS = [
    'gatitu-pcea-youth25.up.railway.app',
    '.gatitu-pcea-youth25.up.railway.app',
    '.railway.app',
    'localhost',
    '127.0.0.1'
]

CSRF_TRUSTED_ORIGINS = [
    'https://gatitu-pcea-youth25.up.railway.app',
    'https://*.railway.app',
    
]

# Cookie settings
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
#CSRF_USE_SESSIONS = False
#CSRF_COOKIE_HTTPONLY = False
#CSRF_COOKIE_DOMAIN = '.railway.app'
# Important for cookie domains
CSRF_COOKIE_DOMAIN = None
SESSION_COOKIE_DOMAIN = None

# Ensure CSRF looks at both HTTP_ORIGIN and HTTP_REFERER
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'public_site',
    'users',
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GatituProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',          
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GatituProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
if 'DATABASE_URL' in os.environ:
    DATABASES = {
        'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGIN_URL = '/users/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ADMIN_SITE_URL = 'admin/'
# Custom user model
AUTH_USER_MODEL = 'users.CustomUser'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'users.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = 'sessionid'
# Email Configuration
if DEBUG:
    # Development: Show emails in console
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production: Use real email
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = 'derrickbaragu@gmail.com'
    EMAIL_HOST_PASSWORD = 'mmvz slaz pbzw yhwd'  # Your App Password
    DEFAULT_FROM_EMAIL = 'derrickbaragu@gmail.com'
    SERVER_EMAIL = 'derrickbaragu@gmail.com'

# Password reset settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours
    
    # Option 2: Use a test file instead of console
    # EMAIL_BACKEND = 'django.core.mail.backends.filebased.EmailBackend'
    # EMAIL_FILE_PATH = BASE_DIR / 'sent_emails'
# Password reset settings
#mmvz slaz pbzw yhwd
PASSWORD_RESET_TIMEOUT = 86400
# Automatic superuser creation for Railway
if 'DJANGO_SUPERUSER_USERNAME' in os.environ:
    from django.core.management import execute_from_command_line
    import sys
    
    # Create superuser automatically
    superuser_username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    superuser_email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    superuser_password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')
    
    # Check if superuser doesn't already exist
    from django.contrib.auth import get_user_model
   # Automatic superuser creation (safe version)

if all(os.environ.get(var) for var in ['DJANGO_SUPERUSER_USERNAME', 'DJANGO_SUPERUSER_EMAIL', 'DJANGO_SUPERUSER_PASSWORD']):
    # This will be handled by Railway's post-deploy hook
    pass

def create_superuser_if_needed():
    # Check if all superuser environment variables exist
    if all(os.environ.get(var) for var in ['DJANGO_SUPERUSER_USERNAME', 'DJANGO_SUPERUSER_EMAIL', 'DJANGO_SUPERUSER_PASSWORD']):
        try:
            # Setup Django
            import django
            django.setup()
            
            from django.contrib.auth import get_user_model
            User = get_user_model()
            
            username = os.environ['DJANGO_SUPERUSER_USERNAME']
            email = os.environ['DJANGO_SUPERUSER_EMAIL']
            password = os.environ['DJANGO_SUPERUSER_PASSWORD']
            
            # Create superuser if it doesn't exist
            if not User.objects.filter(username=username).exists():
                User.objects.create_superuser(
                    username=username,
                    email=email,
                    password=password
                )
                print(f"✅ Superuser '{username}' created successfully!")
            else:
                print(f"ℹ️ Superuser '{username}' already exists")
                
        except Exception as e:
            print(f"❌ Error creating superuser: {e}")

# Run the function
create_superuser_if_needed()

# Database configuration
if all(os.environ.get(var) for var in ['DJANGO_SUPERUSER_USERNAME', 'DJANGO_SUPERUSER_EMAIL', 'DJANGO_SUPERUSER_PASSWORD']):
    # This will be handled by Railway's post-deploy hook
    # Remove the complex function that's causing errors
    pass

# Site URL for password reset links
if DEBUG:
    SITE_URL = 'http://localhost:8000'
else:
    SITE_URL = 'https://gatitu-pcea-youth25.up.railway.app'

# For password reset emails to include correct links
PASSWORD_RESET_TIMEOUT_DAYS = 1

# Check if superuser environment variables exist
if all(os.environ.get(var) for var in ['DJANGO_SUPERUSER_USERNAME', 'DJANGO_SUPERUSER_EMAIL', 'DJANGO_SUPERUSER_PASSWORD']):
    try:
        # Import after Django is ready
        from django.apps import apps
        if apps.ready:
            from django.contrib.auth import get_user_model
            User = get_user_model()
            
            username = os.environ['DJANGO_SUPERUSER_USERNAME']
            email = os.environ['DJANGO_SUPERUSER_EMAIL']
            password = os.environ['DJANGO_SUPERUSER_PASSWORD']
            
            # Create superuser if it doesn't exist
            if not User.objects.filter(username=username).exists():
                User.objects.create_superuser(
                    username=username,
                    email=email,
                    password=password
                )
                print(f"✅ Superuser '{username}' created successfully!")
            else:
                print(f"ℹ️ Superuser '{username}' already exists")
    except Exception as e:
        print(f"⚠️ Could not create superuser automatically: {e}")